# Generated by Django 2.2.9 on 2020-03-22 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='first_symptomatic',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
