version: "3.5"
services:
  postgres:
    container_name: coronavirus_mapper_postgres
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    networks:
      - postgres
    volumes:
      - ./postgres_data:/data/postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge
    